# SPDX-FileCopyrightText: 2014-2021 Agora Voting SL <contact@nvotes.com>
#
# SPDX-License-Identifier: AGPL-3.0-only
---
resolutions:
  rule_violations:
  - message: "The package SpdxDocumentFile::agora-airgap:.* has the declared ScanCode copyleft catalogized license GPL-3.0-only."
    reason: "LICENSE_ACQUIRED_EXCEPTION"
    comment: "The project is open source so it's normal that it's set as such."

  - message: "The package SpdxDocumentFile::(libgmp|wxwidgets):.* has the declared ScanCode copyleft-limited categorized license LGPL-3.0-only."
    reason: "DYNAMIC_LINKAGE_EXCEPTION"
    comment: "We don't modify this related package with LGPL, so it's not viral even if we link to it. See more in: https://en.wikipedia.org/wiki/GNU_Lesser_General_Public_License."
