name: "nix-build"
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2.3.5
    - uses: cachix/install-nix-action@v14
      with:
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.5pre20211015_130284b/install
        nix_path: nixpkgs=channel:nixos-21.05
        extra_nix_config: |
          experimental-features = nix-command flakes

    - name: Print nixpkgs version
      run: nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version'

    - run: nix flake show
    - run: nix flake metadata
    - run: nix flake info
    - run: nix build -L
    - run: nix flake check
