name: "nix-build"
on:
  pull_request:
  push:
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2.3.5
    - uses: cachix/install-nix-action@v14
      with:
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.5pre20211015_130284b/install
        nix_path: nixpkgs=channel:nixos-21.05
        extra_nix_config: |
          experimental-features = nix-command flakes

    - name: Print nixpkgs version
      if: ${{ !env.ACT }}
      run: nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version'

    - name: Show flake
      run: nix --extra-experimental-features "nix-command flakes" flake show

    # in all these nix command we add again the --extra-experimental-features
    # because apparently otherwise it doesn't work with
    # https://github.com/nektos/act
    - name: Show flake metadata
      run: nix --extra-experimental-features "nix-command flakes" flake metadata

    - name: Build the flake
      run: nix --extra-experimental-features "nix-command flakes" build -L
    
    - name: Run the unit tests
      run: |
        nix \
          --extra-experimental-features "nix-command flakes" \
          develop \
          --command bash -c "cmake -G  Ninja . && ninja -v && ninja -v test"

    - name: Run flake check
      run: nix --extra-experimental-features "nix-command flakes" flake check

    - name: Archive artifacts
      if: ${{ !env.ACT }}
      uses: actions/upload-artifact@v2
      with:
        name: agora-airgap-${{ matrix.os }}
        path: /nix/store/*-agora-airgap*
